### ISSUE TITLE
No display issue on postmarketos "none"

### ISSUE THREAD

**Issue by johnelmermin227** [antony-jr/postmarketos-asus-z00l#2]
Hi i was trying installed postmarketOS none variant via pmbootstrap install on my Z00L and it's flashed success but i faced black screen/no display issue!!! Do you have any fixes with this?

**Comment by antony-jr** [comment]
Used the official build guide from postmarketOS? is it 720p or 1080p model? Because my port is only for 720p model.

**Comment by johnelmermin227** [comment]
Yes i used official guide and i'm used of 720p model variant since i used via VM from Xubuntu to install postmarketos

**Comment by johnelmermin227** [comment]
In phosh and plasma-mobile variant i got error command failed exit code 1 while installing at pmbootstrap install at stage 2/4

**Comment by antony-jr** [comment]
That might be a problem.. Seems like the panel is initialized but no gui. Since you do see a black color right? Try installing with no error and flash using pmbootstrap not twrp or something.

**Comment by antony-jr** [comment]
You need to have Phosh, that's the main gui, if you install with no graphical user interface, all you will see is a black screen.

**Comment by johnelmermin227** [comment]
yes that mean system partition or userdata? I'll actually seen lk2nd bootloader until now i seen black screen only...

**Comment by johnelmermin227** [comment]
I no have idea in phosh i'm still getting error in command when it's stuck at 100 in rootfs_asus-z00l at install postmarketos-base...

**Comment by johnelmermin227** [comment]
Do i need only pmbootstrap install after choosing phosh?

**Comment by antony-jr** [comment]
> yes that mean system partition or userdata? I'll actually seen lk2nd bootloader until now i seen black screen only...

Yes, lk2nd only shows up if there is no proper kernel to boot, since you flashed the kernel correctly it boots the kernel but init can't find proper things to start up the gui or a terminal.

There is a bug in lk2nd for this device which makes it impossible to return to lk2nd after flashing a valid kernel, you need to ```fastboot erase boot``` and then flash lk2nd again and start the process all over again with pmbootstrap.

> I no have idea in phosh i'm still getting error in command when it's stuck at 100 in rootfs_asus-z00l at install postmarketos-base...

It's not stuck, it just takes a long time.. since you are in a VM, it's triple the time.

**Comment by antony-jr** [comment]
if you want to confirm if the os is up and running, connect with usb and ssh into the device, you can bring up a terminal that way and see dmesg for any specific errors.

**Comment by johnelmermin227** [comment]
If should i install via system or userdata... Since i install through system in pmos none variant. Userdata is taking too long to flash

**Comment by antony-jr** [comment]
Hmm.. use system I guess.. I last built pmos months ago so I have no memory on the specifics.

**Comment by johnelmermin227** [comment]
It worked on userdata method. Thank you for info i'm just used daily driver on Z00L :)
